/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AAvatar: (typeof import("ant-design-vue/es"))["Avatar"]
    AButton: (typeof import("ant-design-vue/es"))["Button"]
    ADrawer: (typeof import("ant-design-vue/es"))["Drawer"]
    ADropdown: (typeof import("ant-design-vue/es"))["Dropdown"]
    AInput: (typeof import("ant-design-vue/es"))["Input"]
    AMenu: (typeof import("ant-design-vue/es"))["Menu"]
    AMenuItem: (typeof import("ant-design-vue/es"))["MenuItem"]
    ASwitch: (typeof import("ant-design-vue/es"))["Switch"]
    ATabPane: (typeof import("ant-design-vue/es"))["TabPane"]
    ATabs: (typeof import("ant-design-vue/es"))["Tabs"]
  }
}
